name: LoveWebAdmin
version: '${version}'

main: me.lovelace.loveWebAdmin.LoveWebAdmin
api-version: '1.21.11'
load: POSTWORLD
description: Веб-панель администрирования для Love* серверов
authors: [ Lovelace ]
softdepend: [ LuckPerms ]

commands:
  lovewebadmin:
    description: LoveWebAdmin управление
    usage: /lovewebadmin <info|reload|resetowner>
    aliases: [ lwa ]
    permission: lovewebadmin.admin

permissions:
  lovewebadmin.admin:
    description: Доступ к команде /lovewebadmin (алиас /lwa)
    default: op
